# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

skipgram_cpp2 <- function(tokens, ns, skips, delim) {
    .Call('quanteda_skipgram_cpp2', PACKAGE = 'quanteda', tokens, ns, skips, delim)
}

skipgram_cppl2 <- function(x, ns, skips, delim) {
    .Call('quanteda_skipgram_cppl2', PACKAGE = 'quanteda', x, ns, skips, delim)
}

skipgramcpp <- function(tokens, ns, ks, delim) {
    .Call('quanteda_skipgramcpp', PACKAGE = 'quanteda', tokens, ns, ks, delim)
}

wordfishcpp <- function(wfm, dir, priors, tol, disp, dispfloor) {
    .Call('quanteda_wordfishcpp', PACKAGE = 'quanteda', wfm, dir, priors, tol, disp, dispfloor)
}

