# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

skipgramcpp <- function(tokens, ns, ks, delim) {
    .Call('quanteda_skipgramcpp', PACKAGE = 'quanteda', tokens, ns, ks, delim)
}

skip <- function(tokens, start, n, skips, ngram, ngrams, e, f) {
    invisible(.Call('quanteda_skip', PACKAGE = 'quanteda', tokens, start, n, skips, ngram, ngrams, e, f))
}

skipgram_cpp2 <- function(tokens, ns, skips, delim) {
    .Call('quanteda_skipgram_cpp2', PACKAGE = 'quanteda', tokens, ns, skips, delim)
}

skipgram_cppl2 <- function(x, ns, skips, delim) {
    .Call('quanteda_skipgram_cppl2', PACKAGE = 'quanteda', x, ns, skips, delim)
}

bigram_selective_cppl <- function(x, types, types_stop, types_ignore, skips, delim, token_sub) {
    .Call('quanteda_bigram_selective_cppl', PACKAGE = 'quanteda', x, types, types_stop, types_ignore, skips, delim, token_sub)
}

wordfishcpp <- function(wfm, dir, priors, tol, disp, dispfloor) {
    .Call('quanteda_wordfishcpp', PACKAGE = 'quanteda', wfm, dir, priors, tol, disp, dispfloor)
}

